"""add orders payments deliveries

Revision ID: 5edcdeb5d43d
Revises: 1288047327e3
Create Date: 2026-08-21 14:50:34.707967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5edcdeb5d43d'
down_revision: Union[str, None] = '1288047327e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('item_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('payment_method', sa.Enum('MOCK', 'WAVE', 'ORANGE_MONEY', 'MTN_MOBILE_MONEY', 'CARD', name='payment_method'), nullable=False),
    sa.Column('delivery_method', sa.Enum('HOME_DELIVERY', 'PICKUP_POINT', 'HAND_DELIVERY', name='delivery_method'), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'SELLER_CONFIRMATION', 'READY_FOR_DELIVERY', 'SHIPPED', 'DELIVERED', 'BUYER_CONFIRMED', 'COMPLETED', 'CANCELLED', 'DISPUTED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_listing_id'), 'orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tracking_number', sa.String(length=60), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_listing_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
